name: Quickstart suggestion
description: Propose a new quickstart. No promises, but we might just build it!
title: "[Quickstart suggestion]: "
labels: 
  - quickstart_suggestion
  - unreviewed
assignees: 
  - keklundrh
body: 
  - type: markdown 
    attributes: 
      value: | 
        Please use this form to submit your idea for a future AI quickstart! 
  - type: textarea
    attributes: 
      label: Quickstart suggestion
      description: Please describe your vision for a quickstart in as much detail as possible.
      value: | 
        **Please describe your vision for a new quickstart** 
        What would you like to see? 

        **Is your suggestion related to a specific use case? Please describe.**
        A clear description of what the quickstart demonstrates and its value.

        **Describe the solution you'd like to see**
        A clear description of what you want to happen, or how you'd build it.

        **Additional context**
        Add any other context or screenshots about the suggestion here. 
    validations: 
      required: true 
